default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
        exclude_types: [batch]
      - id: mixed-line-ending
        args:
          - --fix=crlf
        types: [batch]
      - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        args:
          - --line-length=120
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.5.0
        args:
          - --max-line-length=120

          - --ignore=E231,W503,E712,D100,D104,D105,D107
          # E231 ignored due to https://github.com/psf/black/issues/1288
          # W503 ignored due to https://github.com/psf/black/blob/master/README.md#line-breaks--binary-operators
          # E712 ignored due to Pandas/Numpy usage https://github.com/PyCQA/pycodestyle/issues/450
          # D100 ignored "Missing docstring in public module", would require docstring at start of every Python file
          # D104 ignored "Missing docstring in public package", as this documentation is currently done in the RST files
          # D105 ignored "Missing docstring in magic method", as this should be unnecessary at the moment.
          # D107 ignored "Missing docstring in __init__", as we document init methods in the class docstring

          # See http://www.pydocstyle.org/en/5.0.1/error_codes.html for flake8-docstrings added checks
          - --docstring-convention=google

          # Ignore missing docstrings in tests
          - --per-file-ignores=*_test.py:D101,D102,D103
  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    # Documentation: https://github.com/timothycrosley/isort#using-isort-to-verify-code
    hooks:
      - id: isort
        args:
          - --multi-line=3
          - --trailing-comma
          - --force-grid-wrap
          - --use-parentheses
          - --line-width=120
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args:
          # Documentation: https://mypy.readthedocs.io/en/stable/command_line.html
          - --ignore-missing-imports  # Included by default. Needed due to missing type annotations for dependencies (e.g. h2o).
          - --strict  # Use default strict settings.
          - --warn-return-any  # Warn about accidentally returning values of type "Any".
          - --warn-unreachable  # Warn about unreachable code paths.
